version: "3.8"

services:
  # postgres:
  #   image: postgres:latest
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"

  # redis:
  #   image: redis:latest
  #   volumes:
  #     - redis_data:/data
  #   ports:
  #     - "6379:6379"

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq
  #   environment:
  #     RABBITMQ_DEFAULT_USER: user
  #     RABBITMQ_DEFAULT_PASS: password
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - "MINIO_SERVER_LISTEN_PORT:9000"
      - "MINIO_SERVER_CONSOLE_PORT:9001"
    networks:
      - minionetwork
    volumes:
      - "minio_data:/data"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}

networks:
  minionetwork:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  minio_data:
    driver: local